---
services:
  db:  
    image: jayaprakashdevops/pythonapplication:dbimage
    deploy:
      replicas: 1
    ports:
      - "3306:3306"

  auth_service:
    image: jayaprakashdevops/pythonapplication:authimage
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    

  book_service:
    image: jayaprakashdevops/pythonapplication:bookimage
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
      
  borrow_service:
    image: jayaprakashdevops/pythonapplication:borrowimage
    deploy:
      replicas: 1
    ports:
      - "5003:5003"

  frontend:
    image: jayaprakashdevops/pythonapplication:frontendimage
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    
    
